web/router.ex
defmodule PhoenixTodoList.Router do
  use PhoenixTodoList.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    if Mix.env == :test do
      plug PhoenixTodoList.Plug.SessionBackdoor
    end
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhoenixTodoList do
    pipe_through :browser # Use the default browser stack

    get "/", ListController, :index

    resources "/lists", ListController do
      resources "/items", ItemController,  only: [:create]
    end
    resources "/items", ItemController, only: [:delete]
    get "/sign_up", UserController, :new
    resources "/users", UserController, only: [:create]
    get "/sign_in", SessionController, :new
    resources "/sessions", SessionController, only: [:create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhoenixTodoList do
  #   pipe_through :api
  # end
end

web/models/list.ex
defmodule PhoenixTodoList.List do
  use PhoenixTodoList.Web, :model

  schema "lists" do
    field :name, :string

    timestamps
  end

  @required_fields ~w(name)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/list_controller.ex
defmodule PhoenixTodoList.ListController do
  use PhoenixTodoList.Web, :controller

  alias PhoenixTodoList.List
  alias PhoenixTodoList.Item

  def index(conn, _params) do
   conn
   |> assign(:lists, Repo.all(PhoenixTodoList.List))
   |> render("index.html")
  end

  def new(conn, _params) do
    changeset = List.changeset(%List{})
    render conn, :new, changeset: changeset
  end

  def create(conn, %{"list" => list_params}) do
    changeset = List.changeset(%List{}, list_params)

    case Repo.insert(changeset) do
      {:ok, list} ->
        conn
        |> put_flash(:info, "Created list!")
        |> redirect(to: list_path(conn, :show, list))
      {:error, changeset} ->
        render(conn, :new, changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    list = Repo.get!(List, id) |> Repo.preload(:items)
    item_changeset = Item.changeset(%Item{})
    render conn, :show, list: list, item_changeset: item_changeset
  end

  def edit(conn, %{"id" => id}) do
    list = Repo.get!(List, id)
    changeset = List.changeset(list)
    render conn, :edit, changeset: changeset, list: list
  end

  def update(conn, %{"id" => id, "list" => list_params}) do
    list = Repo.get!(List, id)
    changeset = List.changeset(list, list_params)

    case Repo.update(changeset) do
      {:ok, list} ->
        conn
        |> put_flash(:info, "Updated list!")
        |> redirect(to: list_path(conn, :show, list))
      {:error, changeset} ->
        render(conn, :edit, changeset: changeset, list: list)
    end
  end

  def delete(conn, %{"id" => id}) do
    list = Repo.get!(List, id)
    Repo.delete!(list)
    conn
    |> put_flash(:info, "List deleted successfully.")
    |> redirect(to: list_path(conn, :index))
  end
end

web/views/list_view.ex
defmodule PhoenixTodoList.ListView do
  use PhoenixTodoList.Web, :view
end

web/templates/list/edit.html.eex
<h1>Edit <%= @list.name %></h1>

<%= render "form.html",
  changeset: @changeset,
  conn: @conn,
  action: list_path(@conn, :update, @list),
  button_text: "Update" %>

web/templates/list/form.html.eex
<%= form_for @changeset, @action, fn f -> %>

  <%= if @changeset.action do %>
    <p>Oops! Something went wrong.</p>
  <% end %>

  <label id="list-name">
    Name: <%= text_input f, :name %>
    <%= error_tag f, :name %>
  </label>

  <%= submit @button_text %>
<% end %>

web/templates/list/index.html.eex
<div id="new-list">
  <%= link "New List", to: list_path(@conn, :new) %>
</div>
<h1>My Lists:</h1>

<ul>
  <%= for list <- @lists do %>
    <li>
      <%= link list.name, to: list_path(@conn, :show, list) %>
    </li>
  <% end %>
</ul>

web/templates/list/new.html.eex
<h1>New List</h1>

<%= render "form.html",
  changeset: @changeset,
  conn: @conn,
  action: list_path(@conn, :create),
  button_text: "Create List" %>

web/templates/list/show.html.eex
<div data-role="list">
  <h1><%= @list.name %></h1>
  <%= link "Edit List", to: list_path(@conn, :edit, @list) %>
  <%= link "Delete List", to: list_path(@conn, :delete, @list), method: :delete %>
</div>

<%= form_for @item_changeset, list_item_path(@conn, :create, @list), fn f -> %>
  <label>
    Name: <%= text_input f, :name %>
  </label>
  <label>
    Content: <%= text_input f, :content %>
  </label>
  <%= submit "Create Item" %>
<% end %>

<ul>
  <%= for item <- @list.items do %>
    <li>
      <div data-role="item">
        <%= item.name %>
        <%= item.content %>
        <%= link "delete", to: item_path(@conn, :delete, item), method: :delete %>
      </div>
    </li>
  <% end %>
</ul>